<a href="https://colab.research.google.com/github/VikramaJahnavi06/Pytorch/blob/main/Pytorch_Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1. Creating tensors:	Tensors can represent almost any kind of data (images, words, tables of numbers).
Getting information from tensors	If you can put information into a tensor, you'll want to get it out too.
2. Manipulating tensors:	Machine learning algorithms (like neural networks) involve manipulating tensors in many different ways such as adding, multiplying, combining.
3. Dealing with tensor shapes:	One of the most common issues in machine learning is dealing with shape mismatches (trying to mix wrong shaped tensors with other tensors).
4. Indexing on tensors:	If you've indexed on a Python list or NumPy array, it's very similar with tensors, except they can have far more dimensions.
5. Mixing PyTorch tensors and NumPy	PyTorch plays with tensors (torch.Tensor), NumPy likes arrays (np.ndarray) sometimes you'll want to mix and match these.
6. Reproducibility	Machine learning is very experimental and since it uses a lot of randomness to work, sometimes you'll want that randomness to not be so random.
Running tensors on GPU	GPUs (Graphics Processing Units) make your code faster, PyTorch makes it easy to run your code on GPUs.

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

Generally image tensors are represented as -> [colour_channels, height, width]

In [2]:
# scaler
scalar = torch.tensor(5)
scalar

tensor(5)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()
# only for scalar this works!

5

In [5]:
vector = torch.tensor([5, 7])
vector.shape

torch.Size([2])

In [6]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [6, 5, 4]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 5, 4]]])

In [7]:
tensor.ndim

3

In [8]:
tensor[0, 2, 2]

tensor(4)

1. Scalar -> 7
2. Vector -> [7 4] or [7 4]T
3. Matrix -> [[7 4],[4, 5]]
4. Tensor -> [[[7 4],[4, 5]]]


In [9]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7422, 0.7335, 0.3795, 0.4250],
         [0.5784, 0.6987, 0.4364, 0.3807],
         [0.9081, 0.7850, 0.1775, 0.0711]]),
 torch.float32)

In [10]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [11]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [12]:
# torch.range is deprecated
zero_to_hundred = torch.arange(start=0, end=100, step =10)
ten_zeros = torch.zeros_like(input=zero_to_hundred)
print(zero_to_hundred)
print(ten_zeros)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [13]:

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in

device - what device is the tensor stored on? (usually GPU or CPU)

In [14]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7031, 0.4731, 0.0511, 0.1194],
        [0.2670, 0.8691, 0.7444, 0.3668],
        [0.1033, 0.6498, 0.5976, 0.9524]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
# tensor value do not change until reassigned
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)
print(tensor)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 2, 3])


In [16]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [17]:
tensor
# still doesn't change

tensor([1, 2, 3])

In [18]:
# .mul is * which is element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [19]:
# @ and .matmul is used for matrix multiplication
tensor @ tensor

tensor(14)

In [20]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
print(tensor_A.type())
# torch.matmul(tensor_A, tensor_B) # (this will error)
torch.matmul(tensor_A, tensor_B.T)

torch.FloatTensor


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [21]:

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(40)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.2139,  0.6996,  0.7585, -0.9974, -1.0103, -0.6174],
        [ 1.8757,  0.3868,  1.7561, -1.8970, -2.8193, -0.2611],
        [ 2.5375,  0.0740,  2.7536, -2.7966, -4.6283,  0.0952]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [22]:
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# Type(function)-> gives in long tensor, dtype(attribute) gives int64
print(f"Dtype: {x.type()} and element: {x[0].dtype}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Dtype: torch.LongTensor and element: torch.int64
Mean: 45.0
Sum: 450


In [23]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [24]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [25]:

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


Method	One-line description
1. torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
2. Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
3. torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
4. torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
5. torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
6. torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [26]:
x = torch.arange(1,9)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [27]:
x.reshape((2,4)), x

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8]))

In [28]:
z = x.reshape((2,4))

# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4],
         [5, 6, 7, 8]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8]))

In [29]:
x[3] = 32
x, z

(tensor([ 5,  2,  3, 32,  5,  6,  7,  8]),
 tensor([[ 5,  2,  3, 32],
         [ 5,  6,  7,  8]]))

In [30]:
x.view((2,4)), x

# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723

(tensor([[ 5,  2,  3, 32],
         [ 5,  6,  7,  8]]),
 tensor([ 5,  2,  3, 32,  5,  6,  7,  8]))

In [31]:
z = x.reshape((2,4))

# Changing z changes x
z[:, 2] = 23
z, x

(tensor([[ 5,  2, 23, 32],
         [ 5,  6, 23,  8]]),
 tensor([ 5,  2, 23, 32,  5,  6, 23,  8]))

In [32]:
x[0] = 100
z, x

(tensor([[100,   2,  23,  32],
         [  5,   6,  23,   8]]),
 tensor([100,   2,  23,  32,   5,   6,  23,   8]))

In [33]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[100,   2,  23,  32,   5,   6,  23,   8],
        [100,   2,  23,  32,   5,   6,  23,   8],
        [100,   2,  23,  32,   5,   6,  23,   8],
        [100,   2,  23,  32,   5,   6,  23,   8]])

In [34]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[100, 100, 100, 100],
        [  2,   2,   2,   2],
        [ 23,  23,  23,  23],
        [ 32,  32,  32,  32],
        [  5,   5,   5,   5],
        [  6,   6,   6,   6],
        [ 23,  23,  23,  23],
        [  8,   8,   8,   8]])

In [35]:
x_stacked[:, 1] = 0
x_stacked, x
# change in x_stacked does not change x

(tensor([[100,   0, 100, 100],
         [  2,   0,   2,   2],
         [ 23,   0,  23,  23],
         [ 32,   0,  32,  32],
         [  5,   0,   5,   5],
         [  6,   0,   6,   6],
         [ 23,   0,  23,  23],
         [  8,   0,   8,   8]]),
 tensor([100,   2,  23,  32,   5,   6,  23,   8]))

In [36]:
x[5] = 500
x_stacked, x

(tensor([[100,   0, 100, 100],
         [  2,   0,   2,   2],
         [ 23,   0,  23,  23],
         [ 32,   0,  32,  32],
         [  5,   0,   5,   5],
         [  6,   0,   6,   6],
         [ 23,   0,  23,  23],
         [  8,   0,   8,   8]]),
 tensor([100,   2,  23,  32,   5, 500,  23,   8]))

In [37]:
x_reshaped = x.reshape((1, 8))
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[100,   2,  23,  32,   5, 500,  23,   8]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([100,   2,  23,  32,   5, 500,  23,   8])
New shape: torch.Size([8])


In [38]:
x_reshaped[:, 5] = -100
x_reshaped, x, x_squeezed

(tensor([[ 100,    2,   23,   32,    5, -100,   23,    8]]),
 tensor([ 100,    2,   23,   32,    5, -100,   23,    8]),
 tensor([ 100,    2,   23,   32,    5, -100,   23,    8]))

In [39]:
x_squeezed[5] = -210
x_reshaped, x, x_squeezed

(tensor([[ 100,    2,   23,   32,    5, -210,   23,    8]]),
 tensor([ 100,    2,   23,   32,    5, -210,   23,    8]),
 tensor([ 100,    2,   23,   32,    5, -210,   23,    8]))

In [40]:
x[5] = -300
x_reshaped, x, x_squeezed

(tensor([[ 100,    2,   23,   32,    5, -300,   23,    8]]),
 tensor([ 100,    2,   23,   32,    5, -300,   23,    8]),
 tensor([ 100,    2,   23,   32,    5, -300,   23,    8]))

In [41]:

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Basically-> reshape, view or even in original array if any change is made, that will affect all others

In [42]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [44]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [45]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [46]:

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [47]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [48]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
# we reassigned tensor above, if you change the tensor, the array stays the same.
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [50]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [52]:

import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8444, 0.6679, 0.2653, 0.3062],
        [0.9484, 0.7883, 0.1237, 0.5320],
        [0.9362, 0.5715, 0.3113, 0.2438]])

Tensor B:
tensor([[0.4826, 0.7555, 0.5521, 0.4097],
        [0.9979, 0.0076, 0.2893, 0.4329],
        [0.1624, 0.0486, 0.7445, 0.5788]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [53]:

import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [54]:

!nvidia-smi

Mon Aug 11 09:53:21 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   67C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [55]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [56]:

# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [57]:

# Count number of devices
torch.cuda.device_count()

1